import type { Metadata } from 'next'
import { Merriweather } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from 'next-themes'
import { Toaster } from '@/components/ui/sonner'

const merriweather = Merriweather({ subsets: ['latin'], weight: ['700'] })

export const metadata: Metadata = {
  title: 'DeMarketIze',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={merriweather.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          {children}
          <Toaster position='top-right' richColors closeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
